ingressSuffix: -test.apps.silver.devops.gov.bc.ca
acapy:
  image:
    pullPolicy: Always
  ledgers.yml:
    - id: bcovrin-test
      is_production: true
      is_write: true
      genesis_url: 'http://test.bcovrin.vonx.io/genesis'
      endorser_did: '4pgFAjnSVKCr7CMfpqDjhu'
      endorser_alias: 'bcovrin-test-endorser'
    - id: bcovrin-dev
      is_production: true
      is_write: true
      genesis_url: 'http://dev.bcovrin.vonx.io/genesis'
      endorser_did: 'N5bxk3jWkpZ2tEaMtjPjPa'
      endorser_alias: 'bcovrin-dev-endorser'
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
tenant_proxy:
  image:
    pullPolicy: Always
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
ingress:
  annotations:
    route.openshift.io/termination: edge
