global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca

vc-authn-oidc:
  image:
    registry: ghcr.io
    repository: bcgov/acapy-vc-authn-oidc
    pullPolicy: IfNotPresent

  acapyTenancyMode: single
  setNonRevoked: true
  invitationLabel: BC Gov SSO Service (Dev)
  useOobLocalDIDService: false

  controller:
    cameraRedirectUrl: wallet_howto
    presentationExpireTime: 300
    sessionTimeout:
      duration: 86400
      config:
        - expired
        - failed
        - abandoned
        - not_started
        - pending
        - verified
    templateDirectory: /app/templates
    useConnectionBasedVerification: true

  useHTTPS: true
  logLevel: INFO

  auth:
    api:
      existingSecret: "vc-authn-oidc-api-key"
    token:
      privateKey:
        existingSecret: "vc-authn-oidc-jwt-token"
  database:
    existingSecret: "vc-authn-oidc-mongodb"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: edge
  acapy:
    image:
      pullPolicy: IfNotPresent
    existingSecret: "vc-authn-oidc-acapy-secret"
    agentSeed:
      existingSecret: "vc-authn-oidc-agent"
    walletStorageCredentials:
      existingSecret: "vc-authn-oidc-postgresql"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    argfile.yml:
      admin-insecure-mode: false
      auto-accept-invites: true
      auto-accept-requests: true
      auto-ping-connection: true
      auto-provision: true
      auto-respond-credential-offer: true
      auto-respond-messages: true
      auto-verify-presentation: true
      genesis-transactions-list: /tmp/ledgers.yml
      log-level: info
      monitor-ping: true
      multitenant-admin: false
      multitenant: false
      public-invites: true
      read-only-ledger: true
      wallet-name: askar-wallet
      wallet-storage-type: postgres_storage
      wallet-type: askar
      webhook-url: 'https://{{ include "vc-authn-oidc.host" . }}/webhooks'
    ledgers.yml:
      - id: BCovrinTest
        is_production: true
        genesis_url: "http://test.bcovrin.vonx.io/genesis"
      - id: CANdyDev
        is_production: true
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/dev/pool_transactions_genesis"
        is_write: true
      - id: CANdyTest
        is_production: true
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/test/pool_transactions_genesis"
      - id: CANdyProd
        is_production: true
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/prod/pool_transactions_genesis"
    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress
  mongodb:
    auth:
      existingSecret: "vc-authn-oidc-mongodb"
    persistence:
      storageClass: netapp-block-standard
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 400m
        memory: 450Mi
    readinessProbe:
      enabled: true
      timeoutSeconds: 10
    livenessProbe:
      enabled: true
      timeoutSeconds: 10
