apiVersion: v2
name: redis-cluster
type: application
version: 11.5.2
appVersion: 7.4.2
dependencies:
  - name: redis-cluster
    version: 11.5.2
    repository: oci://registry-1.docker.io/bitnamicharts/redis-cluster
