default:
  TEMPLATE_PATH: ../templates

  TOB_API_URL: TOBAPIURL
  TOB_APP_URL: TOBAPPURL

  WALLET_SEED_VONX: 000000-technologies-inc_00000000

  INDY_GENESIS_URL: GENESISURL

  LEDGER_PROTOCOL_VERSION: "1.6"
  AUTO_REGISTER_DID: false

### eof ###
