apiVersion: v2
name: traction
description: traction - production
type: application
version: "0.3.2"
appVersion: "0.5.0"
dependencies:
  - name: traction
    version: "0.3.2"
    repository: https://bcgov.github.io/traction
