apiVersion: v2
name: traction
description: traction - production
type: application
version: "0.3.5"
appVersion: "1.1.0"
dependencies:
  - name: traction
    version: "0.3.5"
    repository: https://bcgov.github.io/traction
