---
ingress:
  annotations:
    route.openshift.io/termination: edge
networkPolicy:
  ingress:
    namespaceSelector:
      network.openshift.io/policy-group: ingress

server:
  image:
    repository: ghcr.io/decentralized-identity/didwebvh-server-py
    tag: 0.3.2
    pullPolicy: Always
  host: "registry-sandbox.apps.silver.devops.gov.bc.ca"
  workers: "4"
  policies:
    webvh_version: "1.0"
    webvh_witness: "true"
    webvh_watcher: ""
    webvh_prerotation: "false"
    webvh_portability: "false"
    webvh_endorsement: "true"

  # This is a public key for the default sandbox witness.
  # It belongs to the ditp-demo-issuer Traction Dev tenant.
  # Once endorser service is setup for webvh, we will update this value
  known_witness_key: "did:key:z6Mkv4HY4FAN618A5nybAaySNyvgVVTbCE2ERA2UWkrHWuvQ"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
postgresql:
  commonLabels:
    backup: "false"
    env: sandbox
  primary:
    persistence:
      size: 5Gi
