---
ingress:
  annotations:
    route.openshift.io/termination: edge
  tls:
    - secretName: tdw-server-tls
      hosts:
        - registry-dev.digitaltrust.gov.bc.ca
networkPolicy:
  ingress:
    namespaceSelector:
      network.openshift.io/policy-group: ingress

server:
  image:
    repository: ghcr.io/decentralized-identity/trustdidweb-server-py
    tag: 0.1.1
    pullPolicy: Always
  host: "registry-dev.digitaltrust.gov.bc.ca"
  environment:
    DOMAIN: "registry-dev.digitaltrust.gov.bc.ca"
    ENDORSER_MULTIKEY: "z6MkekByGjKYvP6dpMBJEHt5UN72rKPVoDgzcS9Hoq6bjfr1"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  resources:
    limits:
      cpu: 500m
      memory: 1600Mi
    requests:
      cpu: 300m
      memory: 820Mi
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
postgresql:
  commonLabels:
    backup: "true"
  primary:
    persistence:
      size: 5Gi
