apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: traction-database
spec:
  postgresVersion: 14
  port: 5432

  users:
  - name: acapy
    options: "CREATEDB CREATEROLE"
  - name: walletman
    options: "CREATEDB CREATEROLE"
  - name: pgadmin
    options: SUPERUSER

  instances:
  - name: ha
    replicas: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: grafana-database
                postgres-operator.crunchydata.com/instance-set: ha
            topologyKey: kubernetes.io/hostname
          weight: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: netapp-block-standard
    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 150Mi
    sidecars:
      replicaCertCopy:
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 1m
            memory: 32Mi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 500
          max_slot_wal_keep_size: 128MB
          max_wal_size: 128MB
          min_wal_size: 32MB
          shared_buffers: 250MB
          wal_buffers: "-1"
        pg_hba:
        - host all all 0.0.0.0/0 md5
        - host all all 0.0.0.0/0 trust
        - host all all ::1/128 trust
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "7"
        repo1-retention-full-type: time
      repoHost:
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 256Mi
      repos:
      - name: repo1
        schedules:
          full: 0 8 * * *
          incremental: 0 0,4,12,16,20 * * *
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: netapp-file-backup
      sidecars:
        pgbackrest:
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
  monitoring:
    pgmonitor:
      exporter:
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 1m
            memory: 64Mi
  proxy:
    pgBouncer:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: grafana-database
                  postgres-operator.crunchydata.com/role: pgbouncer
              topologyKey: kubernetes.io/hostname
            weight: 1
      config:
        global:
          client_tls_sslmode: disable
      port: 5432
      replicas: 1
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
  openshift: true
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
