vc-authn-oidc:
  ingressSuffix: .apps.silver.devops.gov.bc.ca
  image:
    repository: ghcr.io/bcgov/acapy-vc-authn-oidc
    pullPolicy: IfNotPresent
  acapyTenancyMode: single
  setNonRevoked: true
  invitationLabel: BC Gov SSO Service
  useOobLocalDIDService: false
  
  controller:
    cameraRedirectUrl: wallet_howto
    presentationExpireTime: 300
    templateDirectory: /app/templates
    useConnectionBasedVerification: false
  
  useHTTPS: true
  logLevel: INFO
  auth:
    api:
      existingSecret: "vc-authn-oidc-api-key"
    token:
      privateKey:
        existingSecret: "vc-authn-oidc-jwt-token"
  database:
    existingSecret: "vc-authn-oidc-mongodb"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: edge
  acapy:
    image:
      pullPolicy: IfNotPresent
    existingSecret: "vc-authn-oidc-acapy-secret"
    agentSeed:
      existingSecret: "vc-authn-oidc-agent"
    walletStorageConfig:
      url: vc-authn-oidc-agent-database-primary:5432
    walletStorageCredentials:
      admin_account: walletman
      existingSecret: "vc-authn-oidc-agent-database"
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: acapy-password
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    argfile.yml:
      admin-insecure-mode: false
      auto-accept-invites: true
      auto-accept-requests: true
      auto-ping-connection: true
      auto-provision: true
      auto-respond-credential-offer: true
      auto-respond-messages: true
      auto-verify-presentation: true
      genesis-transactions-list: /tmp/ledgers.yml
      label: '{{ include "acapy.label" .}}'
      log-level: info
      monitor-ping: true
      multitenant-admin: false
      multitenant: false
      public-invites: true
      read-only-ledger: true
      wallet-name: askar-wallet
      wallet-storage-type: postgres_storage
      wallet-type: askar
      webhook-url: 'https://{{ include "vc-authn-oidc.host" . }}/webhooks'
    ledgers.yml:
      - id: BCovrinTest
        is_production: true
        genesis_url: "http://test.bcovrin.vonx.io/genesis"
      - id: CANdyProd
        is_production: true
        is_write: true
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/prod/pool_transactions_genesis"
    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress
  mongodb:
    auth:
      existingSecret: "vc-authn-oidc-mongodb"
    persistence:
      storageClass: netapp-block-standard
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 400m
        memory: 450Mi
    metrics:
      enabled: true
    readinessProbe:
      enabled: true
      timeoutSeconds: 10
    livenessProbe:
      enabled: true
      timeoutSeconds: 10
  postgresql:
    enabled: false
