name: Build and Deploy VC-AuthN to DEV

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or full SHA to deploy'
        required: false
        default: 'main'

  push:
    branches:
      - main
    paths:
      - "services/vc-authn-oidc/templates/**"

jobs:
  prepare:
    name: Prepare job variables
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.slug.outputs.SHORT_SHA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build_dev:
    needs: [prepare]
    name: "Build BCGov VC-AuthN Controller DEV"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4
      - name: Build VC-AuthN
        uses: ./.github/actions/build_image
        id: builder
        with:
          context: "./services/vc-authn-oidc"
          dockerfile: "./services/vc-authn-oidc/Dockerfile"
          image_name: ${{ github.repository_owner}}/acapy-vc-authn-oidc
          image_tag: dev
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}

  deploy_dev:
    needs: [prepare, build_dev]
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout acapy-vc-authn-oidc
        uses: actions/checkout@v4
        with:
          repository: openwallet-foundation/acapy-vc-authn-oidc
          fetch-depth: 0
          ref: main
          sparse-checkout: |
            charts
          path: acapy-vc-authn-oidc

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.16"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_VC_AUTHN_DEV }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_VC_AUTHN_DEV }}

      - name: Deploy vc-authn-oidc to Development
        run: |
          cp services/vc-authn-oidc/charts/dev/values.yaml ./dev-values.yaml
          yq e -i 'del(.vc-authn-oidc) | . *= load("services/vc-authn-oidc/charts/dev/values.yaml").vc-authn-oidc' ./dev-values.yaml
          helm upgrade --install vc-authn-oidc -f ./dev-values.yaml --set image.tag=dev ./acapy-vc-authn-oidc/charts/vc-authn-oidc --wait
