name: Deploy vc-authn-oidc

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'SHA to deploy'
        required: false
        default: ''

jobs:
  deploy_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: openwallet-foundation/acapy-vc-authn-oidc
          ref: ${{ github.event.inputs.tag || 'main' }}

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/openwallet-foundation/acapy-vc-authn-oidc
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref
            type=sha
      
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.16"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Get Build Info
        id: values
        shell: bash
        run: |
          echo "image_tag=${{ fromJSON(steps.meta.outputs.json).tags[0] }}"
          echo "image_version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
          echo "helm upgrade --install vc-authn-oidc ./services/vc-authn-oidc/charts/dev --set image.tag=${{ steps.meta.outputs.tags }}"
          
      # - name: Deploy to dev
      #   run: |
      #     helm upgrade --install vc-authn-oidc \
      #       ./services/vc-authn-oidc/charts/dev \
      #       --set image.tag=${{ steps.meta.outputs.tags }}
